-- COPILOTO ENTERPRISE 1.4 - MOTOR DE HISTORICOS
-- Crea históricos separados por empresa, sin afectar ventas operativas actuales.

create table if not exists public.ventas_historicas (
  id bigint generated by default as identity primary key,
  empresa_id uuid not null references public.empresa(id) on delete cascade,
  fecha date not null,
  factura text not null,
  cliente text not null,
  vendedor text,
  almacen text,
  base numeric not null default 0,
  iva numeric not null default 0,
  total numeric not null default 0,
  anio integer not null,
  mes integer not null,
  archivo_origen text,
  cargado_por uuid,
  created_at timestamptz not null default now(),
  unique (empresa_id, factura)
);

create table if not exists public.compras_historicas (
  id bigint generated by default as identity primary key,
  empresa_id uuid not null references public.empresa(id) on delete cascade,
  fecha date not null,
  factura_proveedor text not null,
  documento_proveedor text,
  proveedor text not null,
  valor_total numeric not null default 0,
  saldo numeric not null default 0,
  estado text,
  anio integer not null,
  mes integer not null,
  archivo_origen text,
  cargado_por uuid,
  created_at timestamptz not null default now(),
  unique (empresa_id, factura_proveedor, fecha)
);

create table if not exists public.remisiones_historicas (
  id bigint generated by default as identity primary key,
  empresa_id uuid not null references public.empresa(id) on delete cascade,
  fecha date not null,
  remision text not null,
  cliente text,
  estado text,
  referencia text not null,
  descripcion text,
  cantidad numeric not null default 0,
  pendiente_facturar numeric not null default 0,
  facturada numeric not null default 0,
  devuelta numeric not null default 0,
  valor_unitario numeric not null default 0,
  total numeric not null default 0,
  anio integer not null,
  mes integer not null,
  archivo_origen text,
  cargado_por uuid,
  created_at timestamptz not null default now(),
  unique (empresa_id, remision, referencia)
);

create index if not exists idx_ventas_hist_empresa_fecha on public.ventas_historicas(empresa_id, fecha);
create index if not exists idx_ventas_hist_empresa_vendedor on public.ventas_historicas(empresa_id, vendedor);
create index if not exists idx_ventas_hist_empresa_cliente on public.ventas_historicas(empresa_id, cliente);
create index if not exists idx_compras_hist_empresa_fecha on public.compras_historicas(empresa_id, fecha);
create index if not exists idx_remisiones_hist_empresa_fecha on public.remisiones_historicas(empresa_id, fecha);
create index if not exists idx_remisiones_hist_empresa_ref on public.remisiones_historicas(empresa_id, referencia);

alter table public.ventas_historicas enable row level security;
alter table public.compras_historicas enable row level security;
alter table public.remisiones_historicas enable row level security;

-- El navegador no accede directamente; las operaciones pasan por APIs autenticadas con service role.
revoke all on public.ventas_historicas from anon, authenticated;
revoke all on public.compras_historicas from anon, authenticated;
revoke all on public.remisiones_historicas from anon, authenticated;
grant all on public.ventas_historicas to service_role;
grant all on public.compras_historicas to service_role;
grant all on public.remisiones_historicas to service_role;
grant usage, select on all sequences in schema public to service_role;

create or replace function public.resumen_ventas_historicas(p_empresa_id uuid)
returns table(
  anio integer,
  mes integer,
  total_ventas numeric,
  facturas bigint,
  clientes bigint
)
language sql
security definer
set search_path=public
as $$
  select v.anio, v.mes, sum(v.total), count(distinct v.factura), count(distinct v.cliente)
  from public.ventas_historicas v
  where v.empresa_id=p_empresa_id
  group by v.anio,v.mes
  order by v.anio,v.mes;
$$;

revoke all on function public.resumen_ventas_historicas(uuid) from public;
grant execute on function public.resumen_ventas_historicas(uuid) to service_role;

select 'Motor histórico instalado: ventas, compras y remisiones' as resultado;
