"use client";
import {useEffect,useState} from "react";import Link from "next/link";import {usePathname} from "next/navigation";import {supabaseBrowser} from "@/lib/supabase/client";import {Activity,BarChart3,Bot,BriefcaseBusiness,Building2,DatabaseBackup,DollarSign,FileText,Home,LogOut,Menu,Package,Settings,ShieldCheck,Target,UploadCloud,Users,X,AlertTriangle,History} from "lucide-react";
type U={nombre:string;rol:string;empresa_id?:string;es_superadmin?:boolean};
const items=[
{href:"/dashboard",label:"Dashboard",icon:Home,roles:["Administrador","Gerencia General","Gerencia Comercial","Compras","Cartera"]},
{href:"/enterprise",label:"Centro SaaS",icon:BriefcaseBusiness,roles:["Administrador"]},
{href:"/admin",label:"Empresas y usuarios",icon:Building2,roles:["Administrador"]},
{href:"/reportes",label:"Inteligencia",icon:BarChart3,roles:["Administrador","Gerencia General","Gerencia Comercial","Compras","Cartera","Comercial"]},
{href:"/comercial",label:"Comercial 360°",icon:Target,roles:["Administrador","Gerencia General","Gerencia Comercial","Comercial"]},
{href:"/inventario",label:"Compras 360°",icon:Package,roles:["Administrador","Gerencia General","Compras"]},
{href:"/cartera",label:"Cartera 360°",icon:DollarSign,roles:["Administrador","Gerencia General","Cartera","Gerencia Comercial","Comercial"]},
{href:"/ventas-perdidas",label:"Ventas perdidas",icon:AlertTriangle,roles:["Administrador","Gerencia General","Gerencia Comercial","Comercial"]},
{href:"/ia",label:"Director IA",icon:Bot,roles:["Administrador","Gerencia General","Gerencia Comercial","Comercial","Compras","Cartera"]},
{href:"/documentos",label:"Documentos",icon:FileText,roles:["Administrador","Gerencia General","Gerencia Comercial","Compras","Cartera","Comercial"]},
{href:"/cargar-bases",label:"Centro de datos",icon:UploadCloud,roles:["Administrador","Asistente Comercial"]},
{href:"/auditoria",label:"Auditoría",icon:History,roles:["Administrador"]},
{href:"/copias-seguridad",label:"Respaldos",icon:DatabaseBackup,roles:["Administrador"]},
{href:"/diagnostico",label:"Diagnóstico",icon:Activity,roles:["Administrador"]},
{href:"/configuracion",label:"Configuración",icon:Settings,roles:["Administrador"]}
];
export function Sidebar(){const path=usePathname();const [u,setU]=useState<U|null>(null);const [open,setOpen]=useState(false);const [company,setCompany]=useState("Copiloto Enterprise");useEffect(()=>{try{const x=JSON.parse(localStorage.getItem("copiloto_user")||"null");setU(x);const id=localStorage.getItem("active_company_id")||x?.empresa_id;if(id)supabaseBrowser.from("empresa").select("nombre,nombre_comercial").eq("id",id).single().then(({data})=>setCompany(data?.nombre_comercial||data?.nombre||"Copiloto Enterprise"));}catch{}},[]);const allowed=items.filter(i=>i.roles.includes(u?.rol||""));async function logout(){await supabaseBrowser.auth.signOut();localStorage.clear();location.href="/login"}const content=<><div className="px-4 pb-5"><div className="flex items-center gap-3"><div className="flex h-11 w-11 items-center justify-center rounded-2xl bg-gradient-to-br from-blue-500 to-cyan-400 font-black text-white shadow-lg">C</div><div className="min-w-0"><p className="truncate font-black text-white">{company}</p><p className="text-xs text-slate-400">Enterprise Intelligence</p></div></div></div><nav className="flex-1 space-y-1 overflow-y-auto px-3">{allowed.map(i=>{const I=i.icon,active=path===i.href||path.startsWith(i.href+"/");return <Link key={i.href} href={i.href} onClick={()=>setOpen(false)} className={`sidebar-link ${active?"sidebar-link-active":""}`}><I size={18}/><span>{i.label}</span></Link>})}</nav><div className="m-3 rounded-2xl border border-white/10 bg-white/5 p-4"><div className="flex items-center gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-white/10 font-black text-white">{(u?.nombre||"U")[0]}</div><div className="min-w-0 flex-1"><p className="truncate text-sm font-black text-white">{u?.nombre||"Usuario"}</p><p className="truncate text-xs text-slate-400">{u?.rol||"Perfil"}</p></div><button onClick={logout} className="rounded-xl p-2 text-slate-400 hover:bg-white/10 hover:text-white"><LogOut size={17}/></button></div></div></>;return <><div className="sticky top-0 z-40 flex items-center justify-between bg-slate-950 px-4 py-3 lg:hidden"><p className="font-black text-white">{company}</p><button onClick={()=>setOpen(true)} className="rounded-xl bg-white/10 p-2 text-white"><Menu/></button></div><aside className="fixed inset-y-0 left-0 z-30 hidden w-72 flex-col bg-slate-950 pt-6 lg:flex">{content}</aside>{open&&<div className="fixed inset-0 z-50 lg:hidden"><div className="absolute inset-0 bg-slate-950/70" onClick={()=>setOpen(false)}/><aside className="absolute inset-y-0 left-0 flex w-[88%] max-w-sm flex-col bg-slate-950 pt-4"><button className="mb-2 ml-auto mr-3 rounded-xl bg-white/10 p-2 text-white" onClick={()=>setOpen(false)}><X/></button>{content}</aside></div>}</>}
