"use client";
import { AppLayout } from "@/components/Layout";
import { Hero } from "@/components/Hero";
import { KpiCard } from "@/components/KpiCard";
import { useOperation } from "@/lib/use-operation";
import { Area, AreaChart, Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
const money=(v:number)=>new Intl.NumberFormat("es-CO",{style:"currency",currency:"COP",maximumFractionDigits:0}).format(v||0);
export default function Page(){
 const {data,loading,error,load}=useOperation(); const t=data?.totals||{};
 return <AppLayout><Hero title="Dashboard empresarial" subtitle="Ventas, compras, remisiones, cartera e inventario calculados para la empresa activa."/><button className="btn mb-5" onClick={load}>Actualizar</button>{error&&<div className="alert alert-red">{error}</div>}{loading?<div className="card">Consultando históricos y operación...</div>:data?.empty?<div className="card text-center"><h2 className="text-2xl font-black">Sin datos cargados</h2><p className="mt-2 text-slate-500">Use Centro de datos para cargar históricos u operación.</p></div>:<><section className="grid gap-5 md:grid-cols-2 xl:grid-cols-4"><KpiCard title="Ventas" value={money(t.ventas)} subtitle={`Fuente: ${data.source||"-"}`}/><KpiCard title="Compras" value={money(t.compras)}/><KpiCard title="Remisiones" value={money(t.remisiones)} subtitle={`${Number(t.cantidad_remitida||0).toLocaleString("es-CO")} unidades`}/><KpiCard title="Pronóstico próximo mes" value={money(t.pronostico_siguiente_mes)}/><KpiCard title="Clientes" value={t.clientes||0}/><KpiCard title="Facturas" value={t.facturas||0}/><KpiCard title="Ticket promedio" value={money(t.ticket_promedio)}/><KpiCard title="Cartera" value={money(t.cartera)} subtitle={`${t.cartera_critica||0} registros críticos`}/></section><section className="mt-6 grid gap-6 xl:grid-cols-2"><div className="card"><h2 className="text-xl font-black">Ventas mensuales</h2><div className="mt-5 h-72"><ResponsiveContainer width="100%" height="100%"><AreaChart data={(data.ventas_mensuales||[]).map((r:any)=>({...r,ventas:r.ventas/1e6}))}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="mes"/><YAxis/><Tooltip formatter={(v)=>`${Number(v).toFixed(1)} M`}/><Area type="monotone" dataKey="ventas" fill="#93c5fd" stroke="#2563eb"/></AreaChart></ResponsiveContainer></div></div><div className="card"><h2 className="text-xl font-black">Ventas por año</h2><div className="mt-5 h-72"><ResponsiveContainer width="100%" height="100%"><BarChart data={(data.ventas_anuales||[]).map((r:any)=>({...r,ventas:r.ventas/1e6}))}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="anio"/><YAxis/><Tooltip formatter={(v)=>`${Number(v).toFixed(1)} M`}/><Bar dataKey="ventas" fill="#14b8a6" radius={[8,8,0,0]}/></BarChart></ResponsiveContainer></div></div></section></>}</AppLayout>
}
